FROM base_image

COPY llama_cpp_python/requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

COPY llama_cpp_python/ .

RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip3 install llama-cpp-python[server]