FROM base_image

ENV PYTHONPATH "${PYTHONPATH}:/app/stablediffusion"


COPY stable_diffusion/ .

RUN git clone https://github.com/Stability-AI/stablediffusion.git stablediffusion
WORKDIR stablediffusion

RUN python3 -m pip install -r requirements.txt
RUN pip install -e .

WORKDIR ..