FROM base_image

COPY stable_diffusion/requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

COPY stable_diffusion/ .

# RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git stable-diffusion-webui
# RUN chmod +x ./stable-diffusion-webui/webui.sh
# RUN ./stable-diffusion-webui/webui.sh --api --listen --xformers