FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y python3 python3-pip python3-venv nvidia-cuda-toolkit

RUN python3 -m pip install huggingface-hub llama-index langchain openai diffusers transformers accelerate scipy safetensors xformers
