FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y python3 python3-pip nvidia-cuda-toolkit

COPY cuda/requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

COPY cuda/ .
RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip3 install llama-cpp-python[server]